@host=https://localhost:7215

POST https://localhost:7215/auth/register
Content-Type: application/json

{
   "firstName": "first",
   "lastName": "last",
   "email": "email@email.emal",
   "password": "p@ssword"
}